import { motion } from 'framer-motion'
import { ArrowLeft } from 'lucide-react'

type Props = {
  onBack: () => void
}

export function PrivacyPolicy({ onBack }: Props) {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <div className="max-w-3xl mx-auto px-6 py-12">
        <motion.button onClick={onBack}
          className="flex items-center gap-1.5 text-[13px] text-muted-foreground hover:text-foreground transition-colors cursor-pointer mb-8"
          whileHover={{ x: -2 }}>
          <ArrowLeft className="w-3.5 h-3.5" />
          Back
        </motion.button>

        <div className="mb-10">
          <h1 className="text-[28px] font-bold tracking-tight mb-2" style={{ fontFamily: 'Geist, sans-serif' }}>
            Privacy Policy
          </h1>
          <p className="text-[13px] text-muted-foreground">Last updated: April 15, 2026 · Effective: April 15, 2026</p>
        </div>

        <div className="space-y-8 text-[14px] leading-relaxed text-foreground/80">

          <section className="p-4 rounded-xl bg-muted/20 border border-border/40">
            <p className="text-[13px]">
              This Privacy Policy describes how Nuvee collects, uses, and protects your personal data. We are committed to full compliance with the Brazilian General Data Protection Law (LGPD — Lei nº 13.709/2018), the California Consumer Privacy Act (CCPA), and other applicable privacy regulations.
            </p>
          </section>

          <section>
            <h2 className="text-[16px] font-semibold text-foreground mb-3">1. Data Controller</h2>
            <p><strong>Nuvee</strong> is the data controller for personal information collected through the Platform. We are incorporated in the State of Delaware, United States. For LGPD purposes, our Data Protection Officer (DPO) can be reached through our Discord community.</p>
          </section>

          <section>
            <h2 className="text-[16px] font-semibold text-foreground mb-3">2. Data We Collect</h2>
            <div className="space-y-5">
              <div>
                <h3 className="text-[14px] font-semibold text-foreground mb-2">2.1 Account Information</h3>
                <ul className="space-y-1 list-disc list-inside text-foreground/70">
                  <li>Full name and email address</li>
                  <li>Password (stored exclusively as a bcrypt hash — never in plain text)</li>
                  <li>GitHub username and profile information (only if you sign in with GitHub)</li>
                  <li>Two-factor authentication secret (stored encrypted with AES-256-GCM)</li>
                </ul>
              </div>
              <div>
                <h3 className="text-[14px] font-semibold text-foreground mb-2">2.2 Security and Usage Data</h3>
                <ul className="space-y-1 list-disc list-inside text-foreground/70">
                  <li>IP addresses associated with login, 2FA, and other security events</li>
                  <li>User agent (browser/device information) for trusted device management</li>
                  <li>Security audit logs (login attempts, 2FA activations, deployments, deletions)</li>
                  <li>Timestamps of security-relevant actions</li>
                </ul>
              </div>
              <div>
                <h3 className="text-[14px] font-semibold text-foreground mb-2">2.3 Application Data</h3>
                <ul className="space-y-1 list-disc list-inside text-foreground/70">
                  <li>ZIP files uploaded for bot deployment</li>
                  <li>SHA-256 cryptographic hashes of uploaded files</li>
                  <li>Application logs generated by your deployed bots</li>
                  <li>Environment variables and configuration data you provide</li>
                  <li>Container metadata (memory usage, uptime, status)</li>
                </ul>
              </div>
              <div>
                <h3 className="text-[14px] font-semibold text-foreground mb-2">2.4 Data We Do NOT Collect</h3>
                <ul className="space-y-1 list-disc list-inside text-foreground/70">
                  <li>Payment information (no paid plans currently)</li>
                  <li>Behavioral analytics or tracking data</li>
                  <li>Data from third-party advertising networks</li>
                  <li>Biometric data of any kind</li>
                </ul>
              </div>
            </div>
          </section>

          <section>
            <h2 className="text-[16px] font-semibold text-foreground mb-3">3. Legal Basis for Processing (LGPD)</h2>
            <div className="space-y-2">
              {[
                { basis: 'Contract performance', desc: 'Processing necessary to provide the Platform services you requested' },
                { basis: 'Legitimate interest', desc: 'Security monitoring, fraud prevention, and platform integrity' },
                { basis: 'Legal obligation', desc: 'Compliance with applicable laws and cooperation with legal authorities' },
                { basis: 'Consent', desc: 'Where explicitly requested, such as marketing communications' },
              ].map(item => (
                <div key={item.basis} className="flex items-start gap-3 p-3 rounded-lg bg-muted/20 border border-border/20">
                  <div className="min-w-0">
                    <p className="text-[13px] font-medium text-foreground">{item.basis}</p>
                    <p className="text-[12px] text-foreground/60 mt-0.5">{item.desc}</p>
                  </div>
                </div>
              ))}
            </div>
          </section>

          <section>
            <h2 className="text-[16px] font-semibold text-foreground mb-3">4. How We Use Your Data</h2>
            <ul className="space-y-1.5 list-disc list-inside text-foreground/70">
              <li>To create and manage your account and provide Platform services</li>
              <li>To authenticate your identity and protect your account security</li>
              <li>To detect, investigate, and prevent fraudulent or malicious activity</li>
              <li>To comply with legal obligations and respond to lawful requests from authorities</li>
              <li>To maintain and improve Platform performance and reliability</li>
              <li>To send security notifications (e.g., suspicious login alerts)</li>
            </ul>
          </section>

          <section>
            <h2 className="text-[16px] font-semibold text-foreground mb-3">5. Data Storage and Security</h2>
            <ul className="space-y-2 list-disc list-inside text-foreground/70">
              <li>All data is stored exclusively on your own self-hosted server — Nuvee does not have remote access to your data</li>
              <li>Passwords are hashed using bcrypt (minimum cost factor 10)</li>
              <li>2FA secrets are encrypted using AES-256-GCM with PBKDF2 key derivation</li>
              <li>No personal data is shared with third-party services, analytics platforms, or advertisers</li>
              <li>No telemetry or usage data is transmitted to external servers</li>
              <li>Uploaded files are stored in isolated, access-controlled storage</li>
            </ul>
          </section>

          <section>
            <h2 className="text-[16px] font-semibold text-foreground mb-3">6. Data Retention Schedule</h2>
            <div className="overflow-x-auto rounded-xl border border-border/40">
              <table className="w-full text-[13px] border-collapse">
                <thead className="bg-muted/20">
                  <tr>
                    <th className="text-left py-3 px-4 font-semibold text-foreground">Data Type</th>
                    <th className="text-left py-3 px-4 font-semibold text-foreground">Retention Period</th>
                    <th className="text-left py-3 px-4 font-semibold text-foreground">Legal Basis</th>
                  </tr>
                </thead>
                <tbody className="text-foreground/70">
                  {[
                    ['Account data (name, email)', 'Until account deletion', 'Contract'],
                    ['Application logs', '90 days after bot deletion', 'Legitimate interest'],
                    ['Uploaded ZIP files', '90 days (quarantine)', 'Legal obligation'],
                    ['File SHA-256 hashes', 'Indefinitely', 'Legal obligation'],
                    ['Security audit logs', 'Indefinitely', 'Legal obligation'],
                    ['IP address logs', '90 days', 'Legitimate interest'],
                    ['Trusted device tokens', '30 days', 'Consent'],
                    ['2FA recovery codes', 'Until disabled or regenerated', 'Contract'],
                  ].map(([type, period, basis]) => (
                    <tr key={type} className="border-t border-border/20">
                      <td className="py-3 px-4">{type}</td>
                      <td className="py-3 px-4">{period}</td>
                      <td className="py-3 px-4 text-muted-foreground">{basis}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </section>

          <section>
            <h2 className="text-[16px] font-semibold text-foreground mb-3">7. Your Rights Under LGPD and CCPA</h2>
            <p className="mb-3">Depending on your location, you may have the following rights regarding your personal data:</p>
            <div className="space-y-2">
              {[
                { right: 'Access', desc: 'Request confirmation of whether we process your data and obtain a copy' },
                { right: 'Correction', desc: 'Request correction of inaccurate or incomplete personal data' },
                { right: 'Deletion', desc: 'Request deletion of your account and all associated personal data' },
                { right: 'Portability', desc: 'Receive your data in a structured, machine-readable format' },
                { right: 'Restriction', desc: 'Request restriction of processing in certain circumstances' },
                { right: 'Objection', desc: 'Object to processing based on legitimate interest' },
                { right: 'Withdraw consent', desc: 'Withdraw previously given consent at any time' },
              ].map(item => (
                <div key={item.right} className="flex items-start gap-3">
                  <span className="text-primary font-semibold text-[13px] shrink-0 mt-0.5 w-24">{item.right}</span>
                  <span className="text-[13px] text-foreground/70">{item.desc}</span>
                </div>
              ))}
            </div>
            <p className="mt-4 text-[13px] p-3 rounded-lg bg-primary/5 border border-primary/20">
              To exercise these rights, you can delete your account directly from <strong>Profile → Danger Zone</strong>, or contact us via Discord. We will respond within 15 business days as required by the LGPD.
            </p>
          </section>

          <section>
            <h2 className="text-[16px] font-semibold text-foreground mb-3">8. International Data Transfers</h2>
            <p>Nuvee is incorporated in Delaware, USA. If you are located in Brazil or the European Economic Area, please be aware that your data may be processed in the United States. We ensure appropriate safeguards are in place for such transfers in compliance with LGPD Article 33 and applicable international data protection standards.</p>
          </section>

          <section>
            <h2 className="text-[16px] font-semibold text-foreground mb-3">9. Cookies and Similar Technologies</h2>
            <p className="mb-2">The Platform uses the following cookies:</p>
            <div className="space-y-2">
              {[
                { name: 'trusted_device', purpose: 'Stores a token to remember trusted devices for 2FA (30 days)', type: 'Functional' },
              ].map(item => (
                <div key={item.name} className="p-3 rounded-lg bg-muted/20 border border-border/30 text-[12px]">
                  <p className="font-mono text-foreground mb-0.5">{item.name}</p>
                  <p className="text-foreground/60">{item.purpose} · <span className="text-primary">{item.type}</span></p>
                </div>
              ))}
            </div>
          </section>

          <section>
            <h2 className="text-[16px] font-semibold text-foreground mb-3">10. Law Enforcement Requests</h2>
            <p>We may disclose personal data to law enforcement or government authorities when required by a valid court order, subpoena, or other legal process issued by competent authorities in the United States, Brazil, or other applicable jurisdictions. We will endeavor to notify affected users unless prohibited by law or if notification would obstruct an ongoing investigation.</p>
          </section>

          <section>
            <h2 className="text-[16px] font-semibold text-foreground mb-3">11. Children's Privacy</h2>
            <p>The Platform is not directed to individuals under the age of 18. We do not knowingly collect personal data from minors. If you believe we have inadvertently collected data from a minor, please contact us immediately and we will promptly delete such data.</p>
          </section>

          <section>
            <h2 className="text-[16px] font-semibold text-foreground mb-3">12. Changes to This Policy</h2>
            <p>We may update this Privacy Policy periodically. Material changes will be communicated with at least 30 days notice via email or a prominent notice on the Platform. The "Last updated" date at the top of this page reflects the most recent revision. Your continued use of the Platform after the effective date constitutes acceptance of the updated Policy.</p>
          </section>

          <section>
            <h2 className="text-[16px] font-semibold text-foreground mb-3">13. Contact and DPO</h2>
            <p className="mb-2">For privacy-related inquiries, to exercise your rights, or to contact our Data Protection Officer:</p>
            <ul className="space-y-1 list-disc list-inside text-foreground/70">
              <li>Discord: <a href="https://discord.gg/ke5V4NeQ49" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">discord.gg/ke5V4NeQ49</a></li>
              <li>GitHub: <a href="https://github.com/joaojpn/docklys-hosting" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">github.com/joaojpn/docklys-hosting</a></li>
            </ul>
            <p className="mt-3 text-[13px] text-muted-foreground">We will respond to privacy requests within 15 business days as required by the LGPD.</p>
          </section>

        </div>
      </div>
    </div>
  )
}
